number = (input('Digite um número com 4 dígitos: '))
print('Unidade:{}'.format(number[3]))
print('Dezena:{}'.format(number[2]))
print('Centena:{}'.format(number[1]))
print('Milhar:{}'.format(number[0]))
